name: Auto Tag on Push

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    auto-tag:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Fetch all tags
              run: git fetch --tags

            - name: Determine next version
              id: version
              run: |
                  # Find latest tag
                  latest=$(git tag --sort=-v:refname | head -n 1)
                  echo "Latest tag: $latest"
                  if [[ "$latest" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
                    major="${BASH_REMATCH[1]}"
                    minor="${BASH_REMATCH[2]}"
                    patch="${BASH_REMATCH[3]}"
                    new_tag="v$major.$minor.$((patch + 1))"
                  else
                    new_tag="v0.1.0"
                  fi
                  echo "Next tag: $new_tag"
                  echo "tag=$new_tag" >> $GITHUB_OUTPUT

            - name: Set up Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Create and push tag
              run: |
                  git tag ${{ steps.version.outputs.tag }}
                  git push origin ${{ steps.version.outputs.tag }}
